# This is a basic workflow that is manually triggered

name: Manual Publish Nuget

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch     

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Correct for GitVersion
        run: |
          git fetch --tags
          git branch -D master
          git branch -b master main
        
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4   
        with:
          versionSpec: '5.3.x'    
      
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.4
      
      - name: Output version
        run: |
          echo "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
          echo "NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}"
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: https://nuget.pkg.github.com/ni/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
                    
      - name: Resotre Nuget Packages
        run: dotnet restore NationalInstruments.Analyzers.sln
     
      - name: Build App
        run: dotnet build NationalInstruments.Analyzers.sln --configuration release
        
      - name: Run Tests
        run: dotnet test NationalInstruments.Analyzers.sln
                
      - name: Pack Nuget Package
        run: dotnet pack .\src\NationalInstruments.Analyzers\NationalInstruments.Analyzers.csproj -p:NuspecFile=../../build/NI.CSharp.Analyzers.nuspec --no-build -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}-${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}
      
      - name: Publish Nuget Package
        run: dotnet nuget push .\.binaries\NationalInstruments.Analyzers\*.nupkg --skip-duplicate --no-symbols true
        
      - name : Remove master branch
        run: git branch -D master
       
